# Generated by Django 4.2.11 on 2024-06-06 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.TextField(null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('fax_number', models.CharField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('landline', models.CharField(max_length=255, null=True)),
                ('company_type_tego', models.CharField(max_length=30, null=True)),
                ('company_field', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('topic', models.TextField()),
                ('field', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('finalInsurance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TenderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('score', models.FloatField(null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tender')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenderPublicConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity_unit', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderPrivateConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.AddField(
            model_name='tender',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tenderad'),
        ),
        migrations.AddField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_card_number', models.CharField(max_length=255, null=True)),
                ('commercial_registration_number', models.CharField(max_length=255, null=True)),
                ('company_type', models.CharField(max_length=255, null=True)),
                ('company_capital', models.IntegerField(null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_quantity', models.IntegerField(null=True)),
                ('supplying_status', models.CharField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderproduct')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePrivateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderprivateconditions')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('owner_id', models.CharField(max_length=20, null=True)),
                ('onwer_position', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_review_date', models.DateField(null=True)),
                ('product_review_date_status', models.CharField(null=True)),
                ('product_review_status', models.CharField(null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
            options={
                'unique_together': {('tender', 'response')},
            },
        ),
    ]
