# Generated by Django 4.2.11 on 2024-07-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderad',
            name='tender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='api.tender'),
        ),
    ]
