# Generated by Django 4.2.11 on 2024-04-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderad',
            name='title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='topic',
            field=models.TextField(max_length=255),
        ),
    ]
