# Generated by Django 4.2.11 on 2024-06-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='initial_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='finalInsurance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='topic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderadmin',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderadmin',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderprivateconditions',
            name='condition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='quantity_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderproduct',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderpublicconditions',
            name='condition',
            field=models.TextField(null=True),
        ),
    ]
