# Generated by Django 4.2.11 on 2024-04-06 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TenderAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderPrivateConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity_unit', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.CreateModel(
            name='TenderPublicConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='tender',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tenderad'),
        ),
        migrations.AddField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
