<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-04-08 12:13
=======
# Generated by Django 4.2.11 on 2024-04-08 12:21
>>>>>>> origin/fadybranch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderad',
            name='title',
<<<<<<< HEAD
            field=models.TextField(max_length=255),
=======
            field=models.TextField(),
>>>>>>> origin/fadybranch
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='topic',
<<<<<<< HEAD
            field=models.TextField(max_length=255),
=======
            field=models.TextField(),
>>>>>>> origin/fadybranch
        ),
    ]
