# Generated by Django 4.2.11 on 2024-06-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_verified_alter_tender_initial_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderad',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='finalInsurance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
