# Generated by Django 4.2.11 on 2024-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tender_tenderad_tenderadmin_tenderprivateconditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderad',
            name='field',
            field=models.CharField(default='الكترونيا', max_length=255),
            preserve_default=False,
        ),
    ]
