# Generated by Django 4.2.11 on 2024-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tenderad_title_alter_tenderad_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderad',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tenderad',
            name='topic',
            field=models.TextField(),
        ),
    ]