# Generated by Django 4.2.11 on 2024-07-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tenderad_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderresponse',
            name='offered_price',
        ),
    ]
