# Generated by Django 4.2.11 on 2024-03-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_supplier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_type',
            field=models.CharField(default='supplier', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
