# Generated by Django 4.2.11 on 2024-03-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_is_supplier_customuser_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
    ]
