
# Generated by Django 4.2.11 on 2024-04-13 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tenderad_title_alter_tenderad_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_quantity', models.IntegerField()),
                ('product_price', models.IntegerField()),
                ('supplying_duration', models.CharField(max_length=255)),
                ('supplying_status', models.BooleanField()),
                ('product_description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderproduct')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsePrivateCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderresponse')),
            ],
        ),
    ]
