# Generated by Django 4.2.11 on 2024-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tender_initial_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseproductbid',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseproductbid',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='responseproductbid',
            name='provided_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
