POST  http://localhost:8000/register/
Content-Type: application/json

{
    "first_name": "saqer",
    "last_name": "adel", 
    "email": "dasd@gmail.com",
    "mobile_number": "123213",
    "password": "sameradel",
    "password2":"qwe"
}

###


put  http://localhost:8000/companies/
Content-Type: application/json

{
    "owners": [
        {
            "id":44,
            "name": "Not Philib",
            "owner_id": "3020525234234",
            "onwer_position": "not manager",
            "address": "not street xyz"
        }
    ],
    "company_fields": [
        {
            "primary_field": "furniture",
            "secondary_field": "not furniture"
        }
    ],
    "user": {
        "first_name": "nardin",
        "last_name": "philib",
        "email": "tego@gmail.com",
        "mobile_number": "0123654654",
        "password": "sameradel",
        "password2":"sameradel"
    },
    "name": "Samerco inc",
    "location": "not miami",
    "commercial_registration_number": "6345346464",
    "tax_card_number": "423423",
    "mobile": "23423",
    "landline": "9999",
    "fax_number": "7567",
    "company_type": "supplier",
    "company_capital": 123445
}

###


POST  http://localhost:8000/companies/
Content-Type: application/json

{
    "company_fields": [
        {
            "primary_field": "furniture",
            "secondary_field": "not furniture"
        }
    ],
    "user": {
        "first_name": "nardin",
        "last_name": "philib",
        "email": "qweqw@gmail.com",
        "mobile_number": "0123654654",
        "password": "sameradel",
        "password2":"sameradel"
    },
    "name": "Samerco inc",
    "location": "not miami",
    "mobile": "23423",
    "landline": "9999",
    "fax_number": "7567",
    "company_type": "buyer"
}
###



POST  http://localhost:8000/login/
Content-Type: application/json

{

    "email": "sameradel789@gmail.com",
    "password": "sameradel"
}